const verbs = ["be"];
const spells = [
  "Anapneo",
  "Apparate",
  "Arania Exumai",
  "Avis",
  "Brackium Emendo",
  "Episkey",
  "Evanesco",
  "Everte Statum",
  "Ferula",
  "Finite",
  "Finite Incantatem",
  "Flagrate",
  "Homenum Revelio",
  "Inanimatus Conjurus",
  "Incarcerous",
  "Incendio",
  "Lacarnum Inflamari",
  "Lapifors",
  "Legilimens",
  "Liberacorpus",
  "Morsmordre",
  "Obscuro",
  "Orchideous",
  "Periculum",
  "Reparifarge",
  "Seroensortia",
  "Switching Spell",
  "Unbreakable Vow",
  "Vera Verto",
  "Verdillious",
  "Vermillious",
  "Vipera Evanesca",
  "Vulnera Sanentur",
  "Accio",
  "Aguamenti",
  "Alarte Ascendare",
  "Alohomora",
  "Aparecium",
  "Arresto Momentum",
  "Ascendio",
  "Bubblehead Charm",
  "Caterwauling Charm",
  "Cave Inimicum",
  "Cheering Charm",
  "Colloportus",
  "Confundo",
  "Defodio",
  "Deletrius",
  "Deprimo",
  "Depulso",
  "Descendo",
  "Diffindo",
  "Diminuendo",
  "Dissillusionment Charm",
  "Dissendium",
  "Drought Charm",
  "Duro",
  "Engorgio",
  "Erecto",
  "Expecto Patronum",
  "Expelliarmus",
  "Fianto Duri",
  "Fidelius Charm",
  "Glisseo",
  "Harmonia Nectere Passus",
  "Homonculous Charm",
  "Homorphus Charm",
  "Hover Charm",
  "Immobulus",
  "Imperturbable Charm",
  "Impervius",
  "Lumos",
  "Lumos Solem",
  "Mobiliarbus",
  "Mobilicorpus",
  "Muffliato",
  "Nox",
  "Obliteration Charm",
  "Obliviate",
  "Oculus Reparo",
  "Partis Temporus",
  "Permanent Sticking Charm",
  "Peskipiksi Pesternomi",
  "Piertotum Locomotor",
  "Portus",
  "Prior Incantato",
  "Protean Charm",
  "Protego",
  "Quietus",
  "Reducio",
  "Refilling Charm",
  "Rennervate",
  "Reparo",
  "Repello Inimicum",
  "Repello Muggletum",
  "Rictusempra",
  "Riddikulus",
  "Salvio Hexia",
  "Scourgify",
  "Silencio",
  "Sonorus",
  "Specialis Revelio",
  "Spongify",
  "Stupefy",
  "Tergeo",
  "Trace Charm",
  "Unbreakable Charm",
  "Waddiwasi",
  "Wingardium Leviosa",
  "Anteoculatia",
  "Avada Kedavra",
  "Babbling Curse",
  "Bat Bogey Hex",
  "Calvario",
  "Confrigo",
  "Conjuctivitis Curse",
  "Crucio",
  "Densaugeo",
  "Entrail-Expelling Curse",
  "Expulso",
  "Fiendfyre",
  "Flagrante",
  "Furnunculus",
  "Geinio",
  "Horcrux Curse",
  "Impedimenta",
  "Imperio",
  "Langlock",
  "Levicorpus",
  "Locomotor Mortis",
  "Mimble Wimble",
  "Mucus Ad Nauseam",
  "Oppugno",
  "Petrificus Totalus",
  "Reducto",
  "Relashio",
  "Sectumsempra",
  "Slugulus Eructo",
  "Stinging Jinx",
  "Tarantallegra",
  "Transmogrifian Torture",
];

const para = document.body;
const paraInnerHTML = para.innerHTML;

const replaced = paraInnerHTML.replace(
  RegExp(verbs.join("|"), "gm"),
  () => spells[Math.floor(Math.random() * spells.length)]
);

para.innerHTML = replaced;
